{
 "title": "Pull Requests",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pull Requests by User",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by (user) (pull_request)", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "Pull Requests by Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by (status) (pull_request)", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "Total Pull Requests Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pull_request_total" }
   ]
  },
  {
   "title": "Pull Requests Created",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "pull_request" }
   ]
  }
 ]
}